# Generated by Django 4.2.8 on 2023-12-05 10:14

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComunidadAutonoma',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=2)),
                ('nombre', models.CharField(max_length=150)),
                ('nombre_alternativo', models.CharField(blank=True, max_length=150, null=True)),
                ('nombre_slug', models.CharField(blank=True, max_length=150, null=True)),
                ('nombre_alternativo_slug', models.CharField(blank=True, max_length=150, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Comunidad Autónoma',
                'verbose_name_plural': 'Comunidades Autónomas',
                'db_table': 'comunidades_autonomas',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=2)),
                ('nombre', models.CharField(max_length=150)),
                ('nombre_alternativo', models.CharField(blank=True, max_length=150, null=True)),
                ('nombre_slug', models.CharField(blank=True, max_length=150, null=True)),
                ('nombre_alternativo_slug', models.CharField(blank=True, max_length=150, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('comunidad_autonoma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='geopolitico.comunidadautonoma')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'db_table': 'provincias',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=5)),
                ('nombre', models.CharField(max_length=150)),
                ('nombre_alternativo', models.CharField(blank=True, max_length=150, null=True)),
                ('nombre_slug', models.CharField(blank=True, max_length=150, null=True)),
                ('nombre_alternativo_slug', models.CharField(blank=True, max_length=150, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='geopolitico.provincia')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'municipios',
            },
        ),
        migrations.AddIndex(
            model_name='comunidadautonoma',
            index=models.Index(fields=['codigo'], name='comunidades_codigo_e6f522_idx'),
        ),
        migrations.AddIndex(
            model_name='comunidadautonoma',
            index=models.Index(fields=['nombre'], name='comunidades_nombre_4c541f_idx'),
        ),
        migrations.AddIndex(
            model_name='comunidadautonoma',
            index=models.Index(fields=['nombre_alternativo'], name='comunidades_nombre__e5b1c5_idx'),
        ),
        migrations.AddIndex(
            model_name='comunidadautonoma',
            index=models.Index(fields=['nombre_slug'], name='comunidades_nombre__cd7961_idx'),
        ),
        migrations.AddIndex(
            model_name='comunidadautonoma',
            index=models.Index(fields=['nombre_alternativo_slug'], name='comunidades_nombre__3d12f3_idx'),
        ),
        migrations.AddIndex(
            model_name='comunidadautonoma',
            index=models.Index(fields=['nombre', 'nombre_alternativo'], name='comunidades_nombre_900abd_idx'),
        ),
        migrations.AddIndex(
            model_name='comunidadautonoma',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='comunidades_search__64027e_gin'),
        ),
        migrations.AddIndex(
            model_name='provincia',
            index=models.Index(fields=['codigo'], name='provincias_codigo_de35c9_idx'),
        ),
        migrations.AddIndex(
            model_name='provincia',
            index=models.Index(fields=['nombre'], name='provincias_nombre_c435fa_idx'),
        ),
        migrations.AddIndex(
            model_name='provincia',
            index=models.Index(fields=['nombre_alternativo'], name='provincias_nombre__982491_idx'),
        ),
        migrations.AddIndex(
            model_name='provincia',
            index=models.Index(fields=['nombre_slug'], name='provincias_nombre__8f8d77_idx'),
        ),
        migrations.AddIndex(
            model_name='provincia',
            index=models.Index(fields=['nombre_alternativo_slug'], name='provincias_nombre__80f265_idx'),
        ),
        migrations.AddIndex(
            model_name='provincia',
            index=models.Index(fields=['nombre', 'nombre_alternativo'], name='provincias_nombre_882dbe_idx'),
        ),
        migrations.AddIndex(
            model_name='provincia',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='provincias_search__d5330c_gin'),
        ),
        migrations.AddIndex(
            model_name='municipio',
            index=models.Index(fields=['nombre'], name='municipios_nombre_560e90_idx'),
        ),
        migrations.AddIndex(
            model_name='municipio',
            index=models.Index(fields=['codigo'], name='municipios_codigo_e75e56_idx'),
        ),
        migrations.AddIndex(
            model_name='municipio',
            index=models.Index(fields=['nombre_alternativo'], name='municipios_nombre__a34e06_idx'),
        ),
        migrations.AddIndex(
            model_name='municipio',
            index=models.Index(fields=['nombre_slug'], name='municipios_nombre__d3ea65_idx'),
        ),
        migrations.AddIndex(
            model_name='municipio',
            index=models.Index(fields=['nombre_alternativo_slug'], name='municipios_nombre__73c2fd_idx'),
        ),
        migrations.AddIndex(
            model_name='municipio',
            index=models.Index(fields=['nombre', 'nombre_alternativo'], name='municipios_nombre_94335c_idx'),
        ),
        migrations.AddIndex(
            model_name='municipio',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='municipios_search__29aa66_gin'),
        ),
    ]
