# Generated by Django 5.0 on 2023-12-21 13:59

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('professional', 'Profesional'), ('enterprise', 'Enterprise'), ('pay-as-you-go', 'Pago por uso')], default='free', max_length=100),
        ),
        migrations.AlterField(
            model_name='plan',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_plan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='plan',
            table=None,
        ),
        migrations.CreateModel(
            name='MonthlyRequestsPerUser',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('requests', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly requests per user',
                'verbose_name_plural': 'Monthly requests per user',
            },
        ),
    ]
