# Generated by Django 5.0 on 2023-12-21 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_keys', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APIKey',
        ),
    ]
