# Generated by Django 4.2.8 on 2023-12-12 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0012_2_8'),
        ('authentication', '0002_remove_subscription_plan_remove_subscription_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='odsuser',
            name='stripe_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='djstripe.customer'),
        ),
    ]
